name: Python Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python version

    - name: Run Python Script
      run: |
        python helloworld.py  # Replace with the actual script name

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python version

    - name: Install Dependencies
      run: pip install -r requirements.txt  # If you have any dependencies

    - name: Run Tests
      run: |
        if python test_hello_world.py; then
          echo "Test complete"
        else
          echo "Error occurred"
        fi
