name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install xmlrunner
        run: |
          pip install xmlrunner
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run pytest
        run: |
          output=$(python -m pytest -s test_hello_world.py 2>&1)
          echo "::group::Test Output"
          echo "$output"
          if [[ $output == *"1 passed"* ]]; then
            echo "Test case passed"
          else
            echo "Test case failed"
            exit 1
          fi
          echo "::endgroup::
